# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f718e5f9e3655626c4252ff4f17092434c803dc59bf2035fe78cc76ba168ce813abb276e7a5a806964b8276df4a87c93c9c0adcf7e0117d4fa1280f1e0cefb

test:
  secret_key_base: 48ba52f5d5c1621ed16fb9a0c18ef7b29c4cd8a57e3e817ca3343b4d1605d498fa76443e38711cb674c90bbf115f9ed28c52fa62a4b406c078db09960c78389c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
